/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;

/**
 *
 * @author ziez
 */
public class MainFrame1 extends javax.swing.JFrame {

     private String contents;

     /**
      * Creates new form MainFrame
      */
     public MainFrame1() {
          setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());

          initComponents();

     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
          java.awt.GridBagConstraints gridBagConstraints;

          fileChooser = new javax.swing.JFileChooser();
          jToolBar1 = new javax.swing.JToolBar();
          jPanel1 = new javax.swing.JPanel();
          jSplitPane1 = new javax.swing.JSplitPane();
          jPanel2 = new javax.swing.JPanel();
          jTextField1 = new javax.swing.JTextField();
          jButton1 = new javax.swing.JButton();
          jScrollPane1 = new javax.swing.JScrollPane();
          textarea = new javax.swing.JTextArea();
          jPanel3 = new javax.swing.JPanel();
          jTabbedPane1 = new javax.swing.JTabbedPane();
          jScrollPane2 = new javax.swing.JScrollPane();
          jTextArea2 = new javax.swing.JTextArea();
          jScrollPane3 = new javax.swing.JScrollPane();
          jTextArea3 = new javax.swing.JTextArea();
          jScrollPane4 = new javax.swing.JScrollPane();
          jTextArea4 = new javax.swing.JTextArea();
          jTextField2 = new javax.swing.JTextField();
          jButton2 = new javax.swing.JButton();
          jMenuBar1 = new javax.swing.JMenuBar();
          jMenu1 = new javax.swing.JMenu();
          jMenu2 = new javax.swing.JMenu();

          fileChooser.setCurrentDirectory(new java.io.File("/home/ziez/Desktop"));
          fileChooser.setSelectedFile(new java.io.File("/home/ziez/Desktop/SourceCode.java"));

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setTitle("RPL - ZIEZ / 04297");

          jToolBar1.setRollover(true);
          jToolBar1.setPreferredSize(new java.awt.Dimension(13, 10));
          getContentPane().add(jToolBar1, java.awt.BorderLayout.SOUTH);

          jPanel1.setLayout(new java.awt.BorderLayout());

          jSplitPane1.setDividerLocation(300);

          jPanel2.setPreferredSize(new java.awt.Dimension(400, 416));
          jPanel2.setLayout(new java.awt.GridBagLayout());

          jTextField1.setPreferredSize(new java.awt.Dimension(6, 25));
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
          gridBagConstraints.weightx = 2.0;
          gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 5);
          jPanel2.add(jTextField1, gridBagConstraints);

          jButton1.setText("Open");
          jButton1.setMargin(new java.awt.Insets(2, 20, 2, 14));
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
          gridBagConstraints.insets = new java.awt.Insets(5, 0, 10, 5);
          jPanel2.add(jButton1, gridBagConstraints);

          textarea.setColumns(20);
          textarea.setRows(5);
          jScrollPane1.setViewportView(textarea);

          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridy = 1;
          gridBagConstraints.gridwidth = 2;
          gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
          gridBagConstraints.weighty = 2.0;
          gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
          jPanel2.add(jScrollPane1, gridBagConstraints);

          jSplitPane1.setLeftComponent(jPanel2);

          jPanel3.setLayout(new java.awt.GridBagLayout());

          jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
               public void stateChanged(javax.swing.event.ChangeEvent evt) {
                    jTabbedPane1StateChanged(evt);
               }
          });

          jTextArea2.setColumns(20);
          jTextArea2.setRows(5);
          jScrollPane2.setViewportView(jTextArea2);

          jTabbedPane1.addTab("Commentar", jScrollPane2);

          jTextArea3.setColumns(20);
          jTextArea3.setRows(5);
          jScrollPane3.setViewportView(jTextArea3);

          jTabbedPane1.addTab("Variabel", jScrollPane3);

          jTextArea4.setColumns(20);
          jTextArea4.setRows(5);
          jScrollPane4.setViewportView(jTextArea4);

          jTabbedPane1.addTab("Function", jScrollPane4);

          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridy = 0;
          gridBagConstraints.gridwidth = 2;
          gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
          gridBagConstraints.weightx = 2.0;
          gridBagConstraints.weighty = 2.0;
          jPanel3.add(jTabbedPane1, gridBagConstraints);

          jTextField2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
          jTextField2.setText(" ");
          jTextField2.setPreferredSize(new java.awt.Dimension(83, 40));
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridy = 1;
          gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
          gridBagConstraints.weightx = 1.0;
          jPanel3.add(jTextField2, gridBagConstraints);

          jButton2.setText("Pattern");
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridy = 1;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
          gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
          jPanel3.add(jButton2, gridBagConstraints);

          jSplitPane1.setRightComponent(jPanel3);

          jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

          getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

          jMenu1.setText("File");
          jMenuBar1.add(jMenu1);

          jMenu2.setText("Edit");
          jMenuBar1.add(jMenu2);

          setJMenuBar(jMenuBar1);

          setSize(new java.awt.Dimension(800, 600));
          setLocationRelativeTo(null);
     }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          OpenActionPerformed(evt);

          jTextField1.setText(fileChooser.getSelectedFile().getAbsolutePath());

          //   String contents = read(new File("C:\\Users\\LULU\\Documents\\NetBeansProjects\\ERPEEL\\src\\test\\Test2.java"));

          contents = textarea.getText();

          //COMMENTAR
          String slComment = "//[^\r\n]*";
          String mlComment = "/\\*[\\s\\S]*?\\*/";
          String strLit = "\"(?:\\\\.|[^\\\\\"\r\n])*\"";
          String chLit = "'(?:\\\\.|[^\\\\'\r\n])+'";
          String any = "[\\s\\S]";

          Pattern p = Pattern.compile(
                  String.format("(%s)|(%s)|%s|%s|%s", slComment, mlComment, strLit, chLit, any));

          Matcher m = p.matcher(contents);
          while (m.find()) {
               String hit = m.group();
               if (m.group(1) != null) {
                    jTextArea2.append("SingleLine :: " + hit.replace("\n", "\\n") + "\n");
               }
               if (m.group(2) != null) {
                    jTextArea2.append("MultiLine  :: " + hit.replace("\n", "\\n") + "\n");
               }

          }

          //VARIABEL
          // private String variabel;
          String typeVar = "private string \\w*";
          


          Pattern p1 = Pattern.compile(typeVar);

          Matcher m1 = p1.matcher(contents);
          while (m1.find()) {
               String hit = m1.group();
             
                    jTextArea3.append("class name :"+hit +"\n");
             
              

          }


     }//GEN-LAST:event_jButton1ActionPerformed

     private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
          // TODO add your handling code here:
     }//GEN-LAST:event_jTabbedPane1StateChanged

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

          jTextArea3.setText("");
          String variabel = jTextField2.getText();
          Pattern p1 = Pattern.compile(variabel);

          Matcher m1 = p1.matcher(contents);
          while (m1.find()) {
               String hit = m1.group();

               jTextArea3.append(hit);


          }
     }//GEN-LAST:event_jButton2ActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /*
           * Set the Nimbus look and feel
           */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
           * If Nimbus (introduced in Java SE 6) is not available, stay with the
           * default look and feel. For details see
           * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /*
           * Create and display the form
           */
          java.awt.EventQueue.invokeLater(new Runnable() {
               @Override
               public void run() {
                    new MainFrame1().setVisible(true);
               }
          });
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JFileChooser fileChooser;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JMenu jMenu1;
     private javax.swing.JMenu jMenu2;
     private javax.swing.JMenuBar jMenuBar1;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel3;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JScrollPane jScrollPane3;
     private javax.swing.JScrollPane jScrollPane4;
     private javax.swing.JSplitPane jSplitPane1;
     private javax.swing.JTabbedPane jTabbedPane1;
     private javax.swing.JTextArea jTextArea2;
     private javax.swing.JTextArea jTextArea3;
     private javax.swing.JTextArea jTextArea4;
     private javax.swing.JTextField jTextField1;
     private javax.swing.JTextField jTextField2;
     private javax.swing.JToolBar jToolBar1;
     private javax.swing.JTextArea textarea;
     // End of variables declaration//GEN-END:variables

     private void OpenActionPerformed(ActionEvent evt) {

          int returnVal = fileChooser.showOpenDialog(this);
          if (returnVal == JFileChooser.APPROVE_OPTION) {
               File file = fileChooser.getSelectedFile();
               try {

                    textarea.read(new FileReader(file.getAbsolutePath()), null);
               } catch (IOException ex) {
                    System.out.println("problem accessing file" + file.getAbsolutePath());
               }
          } else {
               System.out.println("File access cancelled by user.");
          }
     }

     private String read(File file) throws IOException {
          StringBuilder b = new StringBuilder();
          Scanner scan = new Scanner(file);
          while (scan.hasNextLine()) {
               String line = scan.nextLine();
               b.append(line).append('\n');
          }
          return b.toString();
     }
}
