/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ziez.grafikom.view;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JTable;
import ziez.grafikom.algoritma.d2.Bresenham;
import ziez.grafikom.algoritma.d2.DDA;
import ziez.grafikom.algoritma.d2.Data;
import ziez.grafikom.algoritma.d2.Objek2d;
import ziez.grafikom.algoritma.d2.Transformasi;
import ziez.grafikom.algoritma.d3.Geometry;
import ziez.grafikom.algoritma.d3.Matrix;
import ziez.grafikom.algoritma.d3.Objek3d;

/**
 *
 * @author ziez
 */
public class MainFrame extends javax.swing.JFrame {

    private DDA dda;
    private Bresenham bresenham;
    private JTable tableInfo;
    private DDATabelModel ddaTablemodel;
    private BresenhamTableModel bresenhamTableModel;
    private CardLayout cardToolBox;
    
    private Objek2d objek2d;
    private Objek3d objek3d;

    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {

        initComponents();
        setSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height));
        ddaTablemodel = new DDATabelModel();
        bresenhamTableModel = new BresenhamTableModel();
        tableInfo = new JTable(ddaTablemodel);
        scrollPane.setViewportView(tableInfo);
        dda = new DDA();
        bresenham = new Bresenham();
        cardToolBox =(CardLayout) panelCardToolBox.getLayout();
       objek2d = new Objek2d();
       objek3d = new Objek3d();
       
        panelInfo.setVisible(false);

    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelViewer = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblStep = new javax.swing.JLabel();
        lblDx = new javax.swing.JLabel();
        lblDy = new javax.swing.JLabel();
        lblXinc = new javax.swing.JLabel();
        lblYinc = new javax.swing.JLabel();
        textXinc = new javax.swing.JTextField();
        textStep = new javax.swing.JTextField();
        textDx = new javax.swing.JTextField();
        textDy = new javax.swing.JTextField();
        textYinc = new javax.swing.JTextField();
        panelDraw = new javax.swing.JPanel();
        containerToolBox = new javax.swing.JPanel();
        panelCardToolBox = new javax.swing.JPanel();
        panelToolBoxUTS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textX1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textY1 = new javax.swing.JTextField();
        textY2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textX2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnDDA = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBresenham = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtXc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtYc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRadius = new javax.swing.JTextField();
        btnBreCircle = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtXcElipse = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtYcElipse = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtRx = new javax.swing.JTextField();
        btnBreElipse = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtRy = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        panelToolBoxUAS = new javax.swing.JPanel();
        txtTranslasiY = new javax.swing.JTextField();
        txtTranslasiX = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTranslasi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtScallingSX = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtScallingSY = new javax.swing.JTextField();
        btnScallingMax = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtRotateTheta = new javax.swing.JTextField();
        btnRotate = new javax.swing.JButton();
        btnClearUAS = new javax.swing.JButton();
        panelToolBox3D = new javax.swing.JPanel();
        btnRotate3d = new javax.swing.JButton();
        btnClearUAS1 = new javax.swing.JButton();
        txtRotasi = new javax.swing.JTextField();
        panelSwitch = new javax.swing.JPanel();
        btnUts = new javax.swing.JButton();
        btnUas = new javax.swing.JButton();
        btn3d = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GRAFIKOM-ZIEZ/04297");
        setPreferredSize(new java.awt.Dimension(800, 600));

        panelViewer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Viewer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelViewer.setLayout(new java.awt.BorderLayout());

        panelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Table Info", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelInfo.setPreferredSize(new java.awt.Dimension(212, 220));
        panelInfo.setLayout(new java.awt.BorderLayout());

        scrollPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scrollPane.setPreferredSize(new java.awt.Dimension(100, 120));
        panelInfo.add(scrollPane, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(230, 120));

        lblStep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStep.setText("Step :");

        lblDx.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDx.setText("Dx :");

        lblDy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDy.setText("Dy :");

        lblXinc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblXinc.setText("Xincrement :");

        lblYinc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYinc.setText("Yincrement :");

        textXinc.setEditable(false);

        textStep.setEditable(false);

        textDx.setEditable(false);

        textDy.setEditable(false);

        textYinc.setEditable(false);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblStep)
                        .add(16, 16, 16)
                        .add(textStep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblDx)
                        .add(16, 16, 16)
                        .add(textDx, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblDy)
                        .add(16, 16, 16)
                        .add(textDy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblXinc)
                        .add(16, 16, 16)
                        .add(textXinc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblYinc)
                        .add(16, 16, 16)
                        .add(textYinc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {lblDx, lblDy, lblStep, lblXinc, lblYinc}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textStep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblStep))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textDx, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblDx))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textDy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblDy))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textXinc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblXinc))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textYinc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblYinc))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelInfo.add(jPanel1, java.awt.BorderLayout.WEST);

        panelViewer.add(panelInfo, java.awt.BorderLayout.SOUTH);

        panelDraw.setBackground(new java.awt.Color(254, 254, 254));
        panelDraw.setForeground(new java.awt.Color(255, 0, 0));
        panelDraw.setPreferredSize(new java.awt.Dimension(1000, 1000));
        panelDraw.setLayout(new java.awt.BorderLayout());
        panelViewer.add(panelDraw, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelViewer, java.awt.BorderLayout.CENTER);

        containerToolBox.setLayout(new java.awt.BorderLayout());

        panelCardToolBox.setLayout(new java.awt.CardLayout());

        panelToolBoxUTS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ToolBox", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelToolBoxUTS.setPreferredSize(new java.awt.Dimension(210, 350));

        jLabel1.setText("X1");

        textX1.setText("200");

        jLabel2.setText("Y1");

        textY1.setText("175");

        textY2.setText("10");
        textY2.setNextFocusableComponent(btnDDA);

        jLabel3.setText("Y2");

        textX2.setText("10");

        jLabel4.setText("X2");

        btnDDA.setText("DDALine");
        btnDDA.setNextFocusableComponent(btnClear);
        btnDDA.setPreferredSize(new java.awt.Dimension(80, 28));
        btnDDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDDAActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.setPreferredSize(new java.awt.Dimension(57, 25));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBresenham.setText("BreLine");
        btnBresenham.setPreferredSize(new java.awt.Dimension(70, 28));
        btnBresenham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBresenhamActionPerformed(evt);
            }
        });

        jLabel10.setText("Xc");

        txtXc.setText("200");
        txtXc.setPreferredSize(new java.awt.Dimension(23, 28));

        jLabel11.setText("Yc");

        txtYc.setText("250");
        txtYc.setPreferredSize(new java.awt.Dimension(23, 28));

        jLabel12.setText("Radius");

        txtRadius.setText("50");

        btnBreCircle.setText("BreCircle");
        btnBreCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBreCircleActionPerformed(evt);
            }
        });

        jLabel13.setText("Xc");

        txtXcElipse.setText("200");
        txtXcElipse.setPreferredSize(new java.awt.Dimension(23, 28));

        jLabel14.setText("Yc");

        txtYcElipse.setText("250");
        txtYcElipse.setPreferredSize(new java.awt.Dimension(23, 28));

        jLabel15.setText("Rx");

        txtRx.setText("30");

        btnBreElipse.setText("BreElipse");
        btnBreElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBreElipseActionPerformed(evt);
            }
        });

        txtRy.setText("50");

        jLabel16.setText("Ry");

        org.jdesktop.layout.GroupLayout panelToolBoxUTSLayout = new org.jdesktop.layout.GroupLayout(panelToolBoxUTS);
        panelToolBoxUTS.setLayout(panelToolBoxUTSLayout);
        panelToolBoxUTSLayout.setHorizontalGroup(
            panelToolBoxUTSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelToolBoxUTSLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel10)
                .add(6, 6, 6)
                .add(txtXc, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(jLabel11)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtYc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(149, 149, 149))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator3)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator2)
            .add(jSeparator1)
            .add(panelToolBoxUTSLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(panelToolBoxUTSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelToolBoxUTSLayout.createSequentialGroup()
                        .add(btnBresenham, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnDDA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(btnBreCircle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnBreElipse, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(panelToolBoxUTSLayout.createSequentialGroup()
                        .add(panelToolBoxUTSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(panelToolBoxUTSLayout.createSequentialGroup()
                                .add(jLabel12)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtRadius)
                                .add(2, 2, 2))
                            .add(btnClear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(panelToolBoxUTSLayout.createSequentialGroup()
                                .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtRx, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel16)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtRy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(panelToolBoxUTSLayout.createSequentialGroup()
                                .add(jLabel13)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtXcElipse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel14)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtYcElipse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(panelToolBoxUTSLayout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(textX2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(textY2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(panelToolBoxUTSLayout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(textX1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(textY1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE)))
                .add(147, 147, 147))
        );

        panelToolBoxUTSLayout.linkSize(new java.awt.Component[] {jLabel13, jLabel15}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        panelToolBoxUTSLayout.linkSize(new java.awt.Component[] {jLabel14, jLabel16}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        panelToolBoxUTSLayout.linkSize(new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        panelToolBoxUTSLayout.linkSize(new java.awt.Component[] {textX1, textX2, textY1, textY2, txtRx, txtRy, txtXc, txtXcElipse, txtYc, txtYcElipse}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        panelToolBoxUTSLayout.setVerticalGroup(
            panelToolBoxUTSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelToolBoxUTSLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelToolBoxUTSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(textX1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(textY1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelToolBoxUTSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(textX2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(textY2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelToolBoxUTSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnBresenham, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnDDA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelToolBoxUTSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(txtXc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11)
                    .add(txtYc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(panelToolBoxUTSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(txtRadius, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(btnBreCircle)
                .add(18, 18, 18)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelToolBoxUTSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(txtXcElipse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14)
                    .add(txtYcElipse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelToolBoxUTSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(txtRx, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16)
                    .add(txtRy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(btnBreElipse)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnClear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        panelToolBoxUTSLayout.linkSize(new java.awt.Component[] {textX1, textX2, textY1, textY2, txtRx, txtRy, txtXc, txtXcElipse, txtYc, txtYcElipse}, org.jdesktop.layout.GroupLayout.VERTICAL);

        panelToolBoxUTSLayout.linkSize(new java.awt.Component[] {btnBreCircle, btnBreElipse, btnBresenham, btnClear, btnDDA}, org.jdesktop.layout.GroupLayout.VERTICAL);

        panelCardToolBox.add(panelToolBoxUTS, "toolBoxUTS");

        panelToolBoxUAS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ToolBox", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel5.setText("X");

        jLabel6.setText("Y");

        btnTranslasi.setText("Translasi");
        btnTranslasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranslasiActionPerformed(evt);
            }
        });

        jLabel7.setText("SX");

        jLabel8.setText("SY");

        btnScallingMax.setText("Scalling");
        btnScallingMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScallingMaxActionPerformed(evt);
            }
        });

        jLabel9.setText("T");

        btnRotate.setText("Rotate");
        btnRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotateActionPerformed(evt);
            }
        });

        btnClearUAS.setText("Clear");
        btnClearUAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearUASActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panelToolBoxUASLayout = new org.jdesktop.layout.GroupLayout(panelToolBoxUAS);
        panelToolBoxUAS.setLayout(panelToolBoxUASLayout);
        panelToolBoxUASLayout.setHorizontalGroup(
            panelToolBoxUASLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelToolBoxUASLayout.createSequentialGroup()
                .add(26, 26, 26)
                .add(panelToolBoxUASLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnRotate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(panelToolBoxUASLayout.createSequentialGroup()
                        .add(jLabel9)
                        .add(18, 18, 18)
                        .add(txtRotateTheta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(panelToolBoxUASLayout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtTranslasiX, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(txtTranslasiY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(btnTranslasi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(panelToolBoxUASLayout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtScallingSX, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel8)
                        .add(18, 18, 18)
                        .add(txtScallingSY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(btnScallingMax, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
            .add(panelToolBoxUASLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(panelToolBoxUASLayout.createSequentialGroup()
                    .add(0, 92, Short.MAX_VALUE)
                    .add(btnClearUAS)
                    .add(0, 93, Short.MAX_VALUE)))
        );
        panelToolBoxUASLayout.setVerticalGroup(
            panelToolBoxUASLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelToolBoxUASLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelToolBoxUASLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(txtTranslasiX, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(txtTranslasiY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(btnTranslasi)
                .add(18, 18, 18)
                .add(panelToolBoxUASLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(txtScallingSX, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8)
                    .add(txtScallingSY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(btnScallingMax)
                .add(18, 18, 18)
                .add(panelToolBoxUASLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtRotateTheta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnRotate)
                .addContainerGap(435, Short.MAX_VALUE))
            .add(panelToolBoxUASLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(panelToolBoxUASLayout.createSequentialGroup()
                    .add(0, 341, Short.MAX_VALUE)
                    .add(btnClearUAS)
                    .add(0, 324, Short.MAX_VALUE)))
        );

        panelCardToolBox.add(panelToolBoxUAS, "toolBoxUAS");

        panelToolBox3D.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ToolBox", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnRotate3d.setText("Rotate");
        btnRotate3d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotate3dActionPerformed(evt);
            }
        });

        btnClearUAS1.setText("Clear");
        btnClearUAS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearUAS1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panelToolBox3DLayout = new org.jdesktop.layout.GroupLayout(panelToolBox3D);
        panelToolBox3D.setLayout(panelToolBox3DLayout);
        panelToolBox3DLayout.setHorizontalGroup(
            panelToolBox3DLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelToolBox3DLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(panelToolBox3DLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnRotate3d, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .add(txtRotasi))
                .addContainerGap(40, Short.MAX_VALUE))
            .add(panelToolBox3DLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(panelToolBox3DLayout.createSequentialGroup()
                    .add(0, 92, Short.MAX_VALUE)
                    .add(btnClearUAS1)
                    .add(0, 93, Short.MAX_VALUE)))
        );
        panelToolBox3DLayout.setVerticalGroup(
            panelToolBox3DLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelToolBox3DLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(txtRotasi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnRotate3d)
                .addContainerGap(596, Short.MAX_VALUE))
            .add(panelToolBox3DLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(panelToolBox3DLayout.createSequentialGroup()
                    .add(0, 337, Short.MAX_VALUE)
                    .add(btnClearUAS1)
                    .add(0, 328, Short.MAX_VALUE)))
        );

        panelCardToolBox.add(panelToolBox3D, "toolBox3D");

        containerToolBox.add(panelCardToolBox, java.awt.BorderLayout.CENTER);

        panelSwitch.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnUts.setText("UTS");
        btnUts.setPreferredSize(new java.awt.Dimension(70, 28));
        btnUts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtsActionPerformed(evt);
            }
        });
        panelSwitch.add(btnUts);

        btnUas.setText("UAS");
        btnUas.setPreferredSize(new java.awt.Dimension(70, 28));
        btnUas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUasActionPerformed(evt);
            }
        });
        panelSwitch.add(btnUas);

        btn3d.setText("3D");
        btn3d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3dActionPerformed(evt);
            }
        });
        panelSwitch.add(btn3d);

        containerToolBox.add(panelSwitch, java.awt.BorderLayout.SOUTH);

        getContentPane().add(containerToolBox, java.awt.BorderLayout.EAST);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDDAActionPerformed
        clear();
        dda.setX1(Integer.parseInt(textX1.getText()));
        dda.setY1(Integer.parseInt(textY1.getText()));
        dda.setX2(Integer.parseInt(textX2.getText()));
        dda.setY2(Integer.parseInt(textY2.getText()));

        dda.PlotLine(dda.getX1(), dda.getY1(), dda.getX2(), dda.getY2(), panelDraw.getGraphics());

        textStep.setText("" + dda.getStep());
        textDx.setText("" + dda.getdX());
        textDy.setText("" + dda.getdY());
        textXinc.setText("" + dda.getxIncrement());
        textYinc.setText("" + dda.getyIncrement());

        int i = 1;

        for (Data data : dda.getData()) {
            ddaTablemodel.add(i++, data.getX(), data.getY(), data.getPoint().x, data.getPoint().y);
        }

        tableInfo.setModel(ddaTablemodel);
    }//GEN-LAST:event_btnDDAActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        panelDraw.repaint();
        ddaTablemodel.getAl().clear();
        ddaTablemodel.fireTableDataChanged();
        bresenhamTableModel.getAl().clear();
        bresenhamTableModel.fireTableDataChanged();

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBresenhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBresenhamActionPerformed
        clear();
        bresenham.setX1(Integer.parseInt(textX1.getText()));
        bresenham.setY1(Integer.parseInt(textY1.getText()));
        bresenham.setX2(Integer.parseInt(textX2.getText()));
        bresenham.setY2(Integer.parseInt(textY2.getText()));

        bresenham.plotLine(bresenham.getX1(), bresenham.getY1(), bresenham.getX2(), bresenham.getY2(), panelDraw.getGraphics());

        lblStep.setText("Gradient");
        textStep.setText(""+bresenham.getGr());
        textDx.setText(""+bresenham.getdX());
        textDy.setText(""+bresenham.getdY());
        int i = 0;

        for (Data d : bresenham.getData()) {
            bresenhamTableModel.add(i++, d.getPk(), d.getPoint().x, d.getPoint().y);
        }

        tableInfo.setModel(bresenhamTableModel);
    }//GEN-LAST:event_btnBresenhamActionPerformed

    private void btnBreCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBreCircleActionPerformed
        clear();
        int Xc = Integer.parseInt(txtXc.getText());
        int Yc = Integer.parseInt(txtYc.getText());
        int r = Integer.parseInt(txtRadius.getText());

        bresenham.plotCircle(Xc, Yc, r, panelDraw.getGraphics());

        int i = 1;
        for (Data d : bresenham.getData()) {
            bresenhamTableModel.add(i++, d.getPk(), d.getPoint().x, d.getPoint().y);
        }

        tableInfo.setModel(bresenhamTableModel);
    }//GEN-LAST:event_btnBreCircleActionPerformed

    private void btnBreElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBreElipseActionPerformed
        clear();
        int rx = Integer.parseInt(txtRx.getText());
        int ry = Integer.parseInt(txtRy.getText());
        int Xc = Integer.parseInt(txtXcElipse.getText());
        int Yc = Integer.parseInt(txtYcElipse.getText());

        bresenham.plotElipse(rx, ry, Xc, Yc, panelDraw.getGraphics());

        int i = 1;
        for (Data d : bresenham.getData()) {
            bresenhamTableModel.add(i++, d.getPk(), d.getPoint().x, d.getPoint().y);
        }

        tableInfo.setModel(bresenhamTableModel);
    }//GEN-LAST:event_btnBreElipseActionPerformed

    private void btnUtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtsActionPerformed
        cardToolBox.show(panelCardToolBox, "toolBoxUTS");
     //   panelInfo.setVisible(true);
    }//GEN-LAST:event_btnUtsActionPerformed

    private void btnUasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUasActionPerformed
        cardToolBox.show(panelCardToolBox, "toolBoxUAS");
     //    panelInfo.setVisible(false);
         
         objek2d.DrawObjek(panelDraw.getGraphics());
        

    }//GEN-LAST:event_btnUasActionPerformed

    private void btnTranslasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranslasiActionPerformed
         objek2d = new Objek2d();
         objek2d.DrawObjek(panelDraw.getGraphics());
        Transformasi.translasi(objek2d, Integer.parseInt(txtTranslasiX.getText()),Integer.parseInt(txtTranslasiY.getText()), panelDraw.getGraphics());
    }//GEN-LAST:event_btnTranslasiActionPerformed

    private void btnScallingMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScallingMaxActionPerformed
      objek2d = new Objek2d();
        objek2d.DrawObjek(panelDraw.getGraphics());
        Transformasi.scallingMax(objek2d, Double.parseDouble(txtScallingSX.getText()),Double.parseDouble(txtScallingSY.getText()), panelDraw.getGraphics());
   //      Transformasi.scalling(objek2d,-2,-2, panelDraw.getGraphics());
     
    }//GEN-LAST:event_btnScallingMaxActionPerformed

    private void btnRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotateActionPerformed
       objek2d = new Objek2d();
       objek2d.DrawObjek(panelDraw.getGraphics());
        Transformasi.Rotasi(objek2d, Double.parseDouble(txtRotateTheta.getText()), panelDraw.getGraphics());
    }//GEN-LAST:event_btnRotateActionPerformed

    private void btnClearUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearUASActionPerformed
        objek2d = new Objek2d();
        objek2d.DrawObjek(panelDraw.getGraphics());
        panelDraw.repaint();
       
    }//GEN-LAST:event_btnClearUASActionPerformed

    private void btnRotate3dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotate3dActionPerformed
         //   objek3d.update(objek3d.getGraphics());
        
           Geometry geom = objek3d.getConeGeo();
           Matrix matrix = objek3d.getMatrix8();
           Graphics g = objek3d .getGraphics();
           g.setColor(Color.red);
           
           double t = Double.parseDouble(txtRotasi.getText());
           
          matrix.rotateX(t);
          matrix.rotateY(t);
           matrix.rotateZ(t);
           objek3d.drawGeometry(geom, matrix, g);
         
        
    }//GEN-LAST:event_btnRotate3dActionPerformed

    private void btnClearUAS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearUAS1ActionPerformed
        objek3d.repaint();
    }//GEN-LAST:event_btnClearUAS1ActionPerformed

    private void btn3dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3dActionPerformed
        cardToolBox.show(panelCardToolBox, "toolBox3D");
        panelDraw.add(objek3d);
    }//GEN-LAST:event_btn3dActionPerformed

    private void clear() {

        ddaTablemodel.getAl().clear();
        ddaTablemodel.fireTableDataChanged();
        bresenhamTableModel.getAl().clear();
        bresenhamTableModel.fireTableDataChanged();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn3d;
    private javax.swing.JButton btnBreCircle;
    private javax.swing.JButton btnBreElipse;
    private javax.swing.JButton btnBresenham;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearUAS;
    private javax.swing.JButton btnClearUAS1;
    private javax.swing.JButton btnDDA;
    private javax.swing.JButton btnRotate;
    private javax.swing.JButton btnRotate3d;
    private javax.swing.JButton btnScallingMax;
    private javax.swing.JButton btnTranslasi;
    private javax.swing.JButton btnUas;
    private javax.swing.JButton btnUts;
    private javax.swing.JPanel containerToolBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblDx;
    private javax.swing.JLabel lblDy;
    private javax.swing.JLabel lblStep;
    private javax.swing.JLabel lblXinc;
    private javax.swing.JLabel lblYinc;
    private javax.swing.JPanel panelCardToolBox;
    private javax.swing.JPanel panelDraw;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelSwitch;
    private javax.swing.JPanel panelToolBox3D;
    private javax.swing.JPanel panelToolBoxUAS;
    private javax.swing.JPanel panelToolBoxUTS;
    private javax.swing.JPanel panelViewer;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField textDx;
    private javax.swing.JTextField textDy;
    private javax.swing.JTextField textStep;
    private javax.swing.JTextField textX1;
    private javax.swing.JTextField textX2;
    private javax.swing.JTextField textXinc;
    private javax.swing.JTextField textY1;
    private javax.swing.JTextField textY2;
    private javax.swing.JTextField textYinc;
    private javax.swing.JTextField txtRadius;
    private javax.swing.JTextField txtRotasi;
    private javax.swing.JTextField txtRotateTheta;
    private javax.swing.JTextField txtRx;
    private javax.swing.JTextField txtRy;
    private javax.swing.JTextField txtScallingSX;
    private javax.swing.JTextField txtScallingSY;
    private javax.swing.JTextField txtTranslasiX;
    private javax.swing.JTextField txtTranslasiY;
    private javax.swing.JTextField txtXc;
    private javax.swing.JTextField txtXcElipse;
    private javax.swing.JTextField txtYc;
    private javax.swing.JTextField txtYcElipse;
    // End of variables declaration//GEN-END:variables
}
